import json
import os
import sys
import urllib.request
import urllib.error
from dataclasses import dataclass

# Hidden tag used to find and update an existing Isotrope comment on re-runs
_COMMENT_TAG = "<!-- isotrope-report -->"

# GitHub Actions injects GITHUB_API_URL; defaults to github.com API.
# GitHub Enterprise Server users get the correct URL automatically.
_GITHUB_API_BASE = os.environ.get("GITHUB_API_URL", "https://api.github.com")


@dataclass
class ModelReport:
    file_path: str
    table_ref: str | None      # "DB.SCHEMA.TABLE" or None if not in manifest
    exists: bool
    size_gb: float
    last_altered: str | None
    last_read: str | None


class Reporter:
    def __init__(self, cfg):
        self.github_token = cfg.GITHUB_TOKEN
        self.github_repository = cfg.GITHUB_REPOSITORY
        self.pr_number = cfg.PR_NUMBER

    def build_markdown(self, reports: list[ModelReport]) -> str:
        lines = [
            _COMMENT_TAG,
            "## 🔍 Isotrope: Warehouse Impact Report",
            "",
            f"> **{len(reports)} model(s) deleted or renamed in this PR.** Review before merging.",
            "",
            "| Model | Warehouse Table | Size | Last Altered | Last Read |",
            "| :--- | :--- | ---: | :--- | :--- |",
        ]

        for r in reports:
            model = f"`{r.file_path}`"

            if r.table_ref is None:
                lines.append(f"| {model} | _(not in manifest)_ | — | — | — |")
                continue

            table = f"`{r.table_ref}`"

            if not r.exists:
                lines.append(f"| {model} | {table} | _(not in warehouse)_ | — | — |")
                continue

            size = f"{r.size_gb} GB"
            altered = r.last_altered or "—"
            read = r.last_read or "_(unavailable)_"
            lines.append(f"| {model} | {table} | {size} | {altered} | {read} |")

        lines += [
            "",
            "> ⚠️ Tables with recent reads may have active downstream consumers outside dbt.",
            "",
            "---",
            "_Generated by [Isotrope](https://github.com/your-org/isotrope)_",
        ]

        return "\n".join(lines)

    def publish(self, reports: list[ModelReport]) -> None:
        body = self.build_markdown(reports)

        if self.github_token and self.github_repository and self.pr_number:
            self._post_or_update_pr_comment(body)
        else:
            print(body)

    def _post_or_update_pr_comment(self, body: str) -> None:
        repo = self.github_repository
        pr = self.pr_number
        headers = {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
        }

        existing_id = self._find_existing_comment(repo, pr, headers)

        if existing_id:
            url = f"{_GITHUB_API_BASE}/repos/{repo}/issues/comments/{existing_id}"
            method = "PATCH"
            print(f"📝 Updating existing Isotrope comment #{existing_id}...")
        else:
            url = f"{_GITHUB_API_BASE}/repos/{repo}/issues/{pr}/comments"
            method = "POST"
            print("📝 Posting new Isotrope comment...")

        payload = json.dumps({"body": body}).encode()
        req = urllib.request.Request(url, data=payload, headers=headers, method=method)

        try:
            with urllib.request.urlopen(req) as resp:
                if resp.status in (200, 201):
                    print("✅ PR comment published.")
                else:
                    print(f"⚠️  Unexpected response status: {resp.status}")
        except urllib.error.HTTPError as e:
            print(f"❌ Failed to post PR comment: {e.code} {e.reason}", file=sys.stderr)
            sys.exit(1)

    def _find_existing_comment(self, repo: str, pr: str, headers: dict) -> int | None:
        """
        Returns the comment ID of an existing Isotrope comment, or None.
        Paginates through all pages so PRs with >100 comments are handled correctly.
        """
        url = f"{_GITHUB_API_BASE}/repos/{repo}/issues/{pr}/comments?per_page=100"

        while url:
            req = urllib.request.Request(url, headers=headers)
            try:
                with urllib.request.urlopen(req) as resp:
                    comments = json.loads(resp.read())
                    for comment in comments:
                        if _COMMENT_TAG in comment.get("body", ""):
                            return comment["id"]
                    # Follow pagination via Link header
                    url = _parse_next_link(resp.headers.get("Link", ""))
            except Exception as e:
                print(f"⚠️  Could not fetch existing comments: {e}")
                return None

        return None


def _parse_next_link(link_header: str) -> str | None:
    """Parses the GitHub Link header and returns the 'next' URL if present."""
    if not link_header:
        return None
    for part in link_header.split(","):
        url_part, *rel_parts = part.strip().split(";")
        rel = " ".join(rel_parts).strip()
        if rel == 'rel="next"':
            return url_part.strip().strip("<>")
    return None
